// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: api/find.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CorgiFindRequest_Place int32

const (
	CorgiFindRequest_ATTRACTIONS CorgiFindRequest_Place = 0
	CorgiFindRequest_RESTAURANT  CorgiFindRequest_Place = 1
	CorgiFindRequest_TOILET      CorgiFindRequest_Place = 2
	CorgiFindRequest_ATM         CorgiFindRequest_Place = 3
	CorgiFindRequest_HOTEL       CorgiFindRequest_Place = 4
)

// Enum value maps for CorgiFindRequest_Place.
var (
	CorgiFindRequest_Place_name = map[int32]string{
		0: "ATTRACTIONS",
		1: "RESTAURANT",
		2: "TOILET",
		3: "ATM",
		4: "HOTEL",
	}
	CorgiFindRequest_Place_value = map[string]int32{
		"ATTRACTIONS": 0,
		"RESTAURANT":  1,
		"TOILET":      2,
		"ATM":         3,
		"HOTEL":       4,
	}
)

func (x CorgiFindRequest_Place) Enum() *CorgiFindRequest_Place {
	p := new(CorgiFindRequest_Place)
	*p = x
	return p
}

func (x CorgiFindRequest_Place) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CorgiFindRequest_Place) Descriptor() protoreflect.EnumDescriptor {
	return file_api_find_proto_enumTypes[0].Descriptor()
}

func (CorgiFindRequest_Place) Type() protoreflect.EnumType {
	return &file_api_find_proto_enumTypes[0]
}

func (x CorgiFindRequest_Place) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CorgiFindRequest_Place.Descriptor instead.
func (CorgiFindRequest_Place) EnumDescriptor() ([]byte, []int) {
	return file_api_find_proto_rawDescGZIP(), []int{0, 0}
}

type CorgiFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32                    `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32                    `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Place     CorgiFindRequest_Place     `protobuf:"varint,3,opt,name=place,proto3,enum=find.CorgiFindRequest_Place" json:"place,omitempty"`
	Results   []*CorgiFindRequest_Result `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CorgiFindRequest) Reset() {
	*x = CorgiFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_find_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorgiFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorgiFindRequest) ProtoMessage() {}

func (x *CorgiFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_find_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorgiFindRequest.ProtoReflect.Descriptor instead.
func (*CorgiFindRequest) Descriptor() ([]byte, []int) {
	return file_api_find_proto_rawDescGZIP(), []int{0}
}

func (x *CorgiFindRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CorgiFindRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CorgiFindRequest) GetPlace() CorgiFindRequest_Place {
	if x != nil {
		return x.Place
	}
	return CorgiFindRequest_ATTRACTIONS
}

func (x *CorgiFindRequest) GetResults() []*CorgiFindRequest_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type CorgiFindRequest_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CorgiFindRequest_Result) Reset() {
	*x = CorgiFindRequest_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_find_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorgiFindRequest_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorgiFindRequest_Result) ProtoMessage() {}

func (x *CorgiFindRequest_Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_find_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorgiFindRequest_Result.ProtoReflect.Descriptor instead.
func (*CorgiFindRequest_Result) Descriptor() ([]byte, []int) {
	return file_api_find_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CorgiFindRequest_Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CorgiFindRequest_Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CorgiFindRequest_Result) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_api_find_proto protoreflect.FileDescriptor

var file_api_find_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x66, 0x69, 0x6e, 0x64, 0x22, 0xd1, 0x02, 0x0a, 0x10, 0x63, 0x6f, 0x72, 0x67, 0x69,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x63, 0x6f, 0x72, 0x67,
	0x69, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x69, 0x6e,
	0x64, 0x2e, 0x63, 0x6f, 0x72, 0x67, 0x69, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x1a, 0x4c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x22, 0x48, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x54, 0x54,
	0x52, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45,
	0x53, 0x54, 0x41, 0x55, 0x52, 0x41, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x4f,
	0x49, 0x4c, 0x45, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x54, 0x4d, 0x10, 0x03, 0x12,
	0x09, 0x0a, 0x05, 0x48, 0x4f, 0x54, 0x45, 0x4c, 0x10, 0x04, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_find_proto_rawDescOnce sync.Once
	file_api_find_proto_rawDescData = file_api_find_proto_rawDesc
)

func file_api_find_proto_rawDescGZIP() []byte {
	file_api_find_proto_rawDescOnce.Do(func() {
		file_api_find_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_find_proto_rawDescData)
	})
	return file_api_find_proto_rawDescData
}

var file_api_find_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_find_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_find_proto_goTypes = []interface{}{
	(CorgiFindRequest_Place)(0),     // 0: find.corgiFindRequest.Place
	(*CorgiFindRequest)(nil),        // 1: find.corgiFindRequest
	(*CorgiFindRequest_Result)(nil), // 2: find.corgiFindRequest.Result
}
var file_api_find_proto_depIdxs = []int32{
	0, // 0: find.corgiFindRequest.place:type_name -> find.corgiFindRequest.Place
	2, // 1: find.corgiFindRequest.results:type_name -> find.corgiFindRequest.Result
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_find_proto_init() }
func file_api_find_proto_init() {
	if File_api_find_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_find_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorgiFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_find_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorgiFindRequest_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_find_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_find_proto_goTypes,
		DependencyIndexes: file_api_find_proto_depIdxs,
		EnumInfos:         file_api_find_proto_enumTypes,
		MessageInfos:      file_api_find_proto_msgTypes,
	}.Build()
	File_api_find_proto = out.File
	file_api_find_proto_rawDesc = nil
	file_api_find_proto_goTypes = nil
	file_api_find_proto_depIdxs = nil
}
